release 1.6.22

diff --git a/src/AOloopControl/scripts/aohardsim/aosimmkwf b/src/AOloopControl/scripts/aohardsim/aosimmkwf
--- a/src/AOloopControl/scripts/aohardsim/aosimmkwf
+++ b/src/AOloopControl/scripts/aohardsim/aosimmkwf
@@ -1,130 +1,110 @@
 #!/bin/bash
 
+execname="./AOloopControl"
 
 # number of arguments to script
 NBARGS=0
 
+pname=`echo "$0" | sed "s/\.\///g"`
 
-
-
-
-
+CONFFILE="$pname.conf" #default
 
 function printHELP {
 echo "------------------------------------------------------------------------"
-echo "$(tput bold) GENERATE ATMOSPHERIC WAVEFRONTS $(tput sgr0)"
+echo "$(tput bold) $pname : CREATE WF SEQUENCE$(tput sgr 0)"
 echo "------------------------------------------------------------------------"
-echo "  Create WF series"
+echo "  Creates properly sized wavefronts from pre-computed wavefronts"
 echo "   "
-echo " $(tput bold)USAGE:$(tput sgr0)"
-echo "     $0 [-h]"
+echo " $(tput bold)USAGE:$(tput sgr 0)"
+echo "     $0 [-hc]"
 echo ""
-echo " $(tput bold)OPTIONS:$(tput sgr0)"
-echo "     $(tput bold)-h$(tput sgr0)          help"
+echo " $(tput bold)OPTIONS:$(tput sgr 0)"
+echo "    $(tput bold)-h$(tput sgr 0)               print help"
+echo "    $(tput bold)-c$(tput sgr 0) <conffile>    use configuration file <conffile>"
+echo "    $(tput bold)-n$(tput sgr 0)               create new template default configuration ($CONFFILE.default) and exit"
 echo ""
+echo " $(tput bold)INPUT:$(tput sgr 0)"
+echo "     aosim.conf     configuration file (default name)"
+echo
+echo " $(tput bold)OUTPUT:$(tput sgr 0)"
+echo "     dm05dispmap    shared memory DM displacement map"
 echo ""
 echo "------------------------------------------------------------------------"
 }
 
 
-printHELP1 ()
-{
-    printf "%20s       Create WF series\n" "$0" 
+
+function CreateDefaultConfiguration {
+$execname << EOF
+AOsimmkWF "$CONFFILE"
+exit
+EOF
 }
-
-
-
-EXITSTATUS=0
-
 
 
 # ================= OPTIONS =============================
 
+#Parse command line flags
+#If an option should be followed by an argument, it should be followed by a ":".
+#Notice there is no ":" after "h". The leading ":" suppresses error messages from
+#getopts. This is required to get unrecognized option code to work.
 
-
-
-# Transform long options to short ones
-singlelinehelp=0
-for arg in "$@"; do
-  shift
-  case "$arg" in
-    "--help") set -- "$@" "-h" ;;
-    "--help1") 
-set -- "$@" "-h" 
-singlelinehelp=1;
-;;
-    *)        set -- "$@" "$arg"
-  esac
-done
-
-
-
-
-while getopts :hH:L:N:Cc FLAG; do
+while getopts :hc:n FLAG; do
   case $FLAG in
     h)  #show help
-      if [ "$singlelinehelp" -eq "0" ]; then
       printHELP
-      else
-      printHELP1
-      fi
       exit
       ;;
- 
+    c) # set configuration file name
+    CONFFILE=$OPTARG
+    ;;
+    n) # create default configuration
+    CreateDefaultConfiguration
+    exit
+    ;;
     \?) #unrecognized option - show help
       echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
       printHELP
+      #If you just want to display a simple error message instead of the full
+      #help, remove the 2 lines above and uncomment the 2 lines below.
+      #echo -e "Use ${BOLD}$SCRIPT -h${NORM} to see the help documentation."\\n
+      #exit 2
       ;;
   esac
 done
 
-shift $((OPTIND-1))  
+shift $((OPTIND-1))  #This tells getopts to move on to the next argument.
 
-
-
-
-
+### End getopts code ###
 
 
 
 
 if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
 if [ "$#" -ne $NBARGS ]; then
-    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
+    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr 0)"
 fi
 printHELP
         exit
 fi
 
 
-
-
-
-
-
-
-if [ $EXITSTATUS -eq 1 ]; then
-echo ""
-echo "$(tput setaf 1)$(tput bold) REQUIRED FILES, COMMANDS NOT FOUND: EXITING $(tput sgr0)"
-echo ""
-exit
-else
-echo ""
+if [ ! -f $CONFFILE ]
+  then
+    echo "$(tput setaf 5)$(tput bold) WARNING: File $CONFFILE not found $(tput sgr 0)"
+    echo "$(tput setaf 5)$(tput bold) WARNING: Copying $pname.conf.default to $CONFFILE  $(tput sgr 0)"
+    if [ -f "$pname.conf.default" ]; then
+    cp $pname.conf.default $CONFFILE
+    else
+    echo "$(tput setaf 5)$(tput bold) WARNING: File $pname.conf.default not found $(tput sgr 0) -> creating it"
+    CreateDefaultConfiguration
+    cp $pname.conf.default $CONFFILE
+    fi
 fi
 
 
 
-
-# ======================= SCRIPT CODE STARTS HERE =================================
-
-
-
-
-
-srcdir=$( cat .scripts_src_dir.conf )
-mkdir atmwf
-cp $srcdir/../../AtmosphericTurbulence/scripts/runturb ./atmwf/
-cd atmwf
-./runturb -e ../AOloopControl 1.650
-
-
+$execname -n $pname << EOF
+AOsimmkWF "$CONFFILE"
+exit
+EOF
